# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/mapper/crypt-pv";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."crypt-pv".device = "/dev/disk/by-uuid/15e9f417-b35a-40fe-a066-595be13cf230";

  fileSystems."/home" =
    {
      device = "/dev/mapper/crypt-pv";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/mapper/crypt-pv";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/etc" =
    {
      device = "/dev/mapper/crypt-pv";
      fsType = "btrfs";
      options = [ "subvol=etc" ];
    };

  fileSystems."/var" =
    {
      device = "/dev/mapper/crypt-pv";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/1425-B41E";
      fsType = "vfat";
    };

  fileSystems."/home/nathan/Music" = {
    device = "10.0.0.139:/mnt/tank/root/nathan/music";
    fsType = "nfs";
  };

  swapDevices =
    [{
      device = "/dev/disk/by-partuuid/f9d26ecd-7df5-48ad-bc19-b9ac4e91b0ee";
      randomEncryption = {
        cipher = "aes-xts-plain64";
        enable = true;
        source = "/dev/random";
      };
    }];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
