# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "virtio_pci" "virtio_scsi" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/88f5bc7a-0101-4f10-8863-25def54bab4b";
      fsType = "btrfs";
      options = [ "subvol=root,compress-force=zstd:1" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/61AB-C10E";
      fsType = "vfat";
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/88f5bc7a-0101-4f10-8863-25def54bab4b";
      fsType = "btrfs";
      options = [ "subvol=home,compress-force=zstd:1" ];
    };

  fileSystems."/etc" =
    {
      device = "/dev/disk/by-uuid/88f5bc7a-0101-4f10-8863-25def54bab4b";
      fsType = "btrfs";
      options = [ "subvol=etc,compress-force=zstd:1" ];
    };

  fileSystems."/var" =
    {
      device = "/dev/disk/by-uuid/88f5bc7a-0101-4f10-8863-25def54bab4b";
      fsType = "btrfs";
      options = [ "subvol=var,compress-force=zstd:1" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/88f5bc7a-0101-4f10-8863-25def54bab4b";
      fsType = "btrfs";
      options = [ "subvol=nix,compress-force=zstd:6" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/09eb9e97-3105-4b60-88f7-ac3a01a2c130"; }];

}
