# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/49959c20-a0d0-4b9b-b5bc-f7601640d252";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/68FE-F04C";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/49959c20-a0d0-4b9b-b5bc-f7601640d252";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/var" =
    {
      device = "/dev/disk/by-uuid/49959c20-a0d0-4b9b-b5bc-f7601640d252";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/49959c20-a0d0-4b9b-b5bc-f7601640d252";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/etc" =
    {
      device = "/dev/disk/by-uuid/49959c20-a0d0-4b9b-b5bc-f7601640d252";
      fsType = "btrfs";
      options = [ "subvol=etc" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/522c68bd-b23b-487d-80e3-fc41e2be130f"; }];

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
